[package]
name = "launcher-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
futures.workspace = true
sha1.workspace = true
hex.workspace = true
md5.workspace = true
uuid.workspace = true
dirs.workspace = true
zip.workspace = true
once_cell.workspace = true

[dev-dependencies]
tokio = { workspace = true }
sha1.workspace = true
hex.workspace = true
zip.workspace = true
serde_json.workspace = true
